version: "3.7"
networks:
  crawler:
    driver: "bridge"

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/var/www/html
    restart: always
    networks:
      - crawler
